apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-service
spec:
  template:
    spec:
      containers:
        - name: pet-service
          env:
            - name: ENVIRONMENT
              value: "dev"
            - name: AWS_REGION
              value: "us-west-2"
            - name: DB_CONNECTION_POOL_MAX
              value: "500"
            - name: DB_CONNECTION_POOL_MIN
              value: "50"
            - name: DB_CONNECTION_IDLE_TIMEOUT_MS
              value: "60000"
            - name: DB_CONNECTION_TIMEOUT_MS
              value: "5000"
            - name: DB_MAX_PENDING_REQUESTS
              value: "1000"
          image: 304930966996.dkr.ecr.us-west-2.amazonaws.com/pet-hospital-pet-service:88c71791561ef9592ff646876bddd38a1dea8e36
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospital-service
spec:
  template:
    spec:
      containers:
        - name: hospital-service
          env:
            - name: ENVIRONMENT
              value: "dev"
            - name: AWS_REGION
              value: "us-west-2"
            - name: DB_CONNECTION_POOL_MAX
              value: "500"
            - name: DB_CONNECTION_POOL_MIN
              value: "50"
            - name: DB_CONNECTION_IDLE_TIMEOUT_MS
              value: "60000"
            - name: DB_CONNECTION_TIMEOUT_MS
              value: "5000"
            - name: DB_MAX_PENDING_REQUESTS
              value: "1000"
          image: 304930966996.dkr.ecr.us-west-2.amazonaws.com/pet-hospital-hospital-service:88c71791561ef9592ff646876bddd38a1dea8e36
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-service
spec:
  template:
    spec:
      containers:
        - name: doctor-service
          env:
            - name: ENVIRONMENT
              value: "dev"
            - name: AWS_REGION
              value: "us-west-2"
            - name: DB_CONNECTION_POOL_MAX
              value: "500"
            - name: DB_CONNECTION_POOL_MIN
              value: "50"
            - name: DB_CONNECTION_IDLE_TIMEOUT_MS
              value: "60000"
            - name: DB_CONNECTION_TIMEOUT_MS
              value: "5000"
            - name: DB_MAX_PENDING_REQUESTS
              value: "1000"
          image: 304930966996.dkr.ecr.us-west-2.amazonaws.com/pet-hospital-doctor-service:88c71791561ef9592ff646876bddd38a1dea8e36
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  template:
    spec:
      containers:
        - name: frontend
          env:
            - name: ENVIRONMENT
              value: "dev"
            - name: API_URL
              value: "http://frontend-ingress"
          image: 304930966996.dkr.ecr.us-west-2.amazonaws.com/pet-hospital-frontend:88c71791561ef9592ff646876bddd38a1dea8e36
