---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pet-service-sa
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hospital-service-sa
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: doctor-service-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: service-reader
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pet-service-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: pet-service-sa
  namespace: default
roleRef:
  kind: Role
  name: service-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hospital-service-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: hospital-service-sa
  namespace: default
roleRef:
  kind: Role
  name: service-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: doctor-service-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: doctor-service-sa
  namespace: default
roleRef:
  kind: Role
  name: service-reader
  apiGroup: rbac.authorization.k8s.io
